version: '3.3'

services:    
    vpn:        
        container_name: wireguard-pia
        hostname: wireguard-pia
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia-dat:/pia
        ports:
            - 9091:8080
        cap_add:
            - NET_ADMIN
        environment:
            - LOCAL_NETWORK=192.168.20.0/24
            - LOC=us_south_west
            - USER=${USER}
            - PASS=${PASS}
            - PORT_FORWARDING=1
            - VPNDNS=1.1.1.1,8.8.8.8
            - KEEPALIVE=25
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        dns:
            - 1.1.1.1
            - 8.8.8.8

    qbittorrent:
        container_name: qbittorrent
#        hostname: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        network_mode: "service:vpn"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${CONFIG_DIRECTORY}/qbittorrent:/config
            - ${STORAGE_DIRECTORY}/downloads:/downloads
            - ${STORAGE_DIRECTORY}/downloads:/data
    sonarr:
        container_name: sonarr
        hostname: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        volumes:
            - ${CONFIG_DIRECTORY}/sonarr:/config
            - ${STORAGE_DIRECTORY}/downloads:/data
            - ${STORAGE_DIRECTORY}/video/tv:${STORAGE_DIRECTORY}/video/tv
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "8989:8989"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}

    radarr:
        container_name: radarr
        hostname: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        volumes:
            - ${CONFIG_DIRECTORY}/radarr:/config
            - ${STORAGE_DIRECTORY}/downloads:/data
            - ${STORAGE_DIRECTORY}/video/movie:${STORAGE_DIRECTORY}/video/movie
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "7878:7878"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    lidarr:
        image: lscr.io/linuxserver/lidarr
        container_name: lidarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${CONFIG_DIRECTORY}/lidarr/config:/config
            - ${STORAGE_DIRECTORY}/audio:/music
            - ${STORAGE_DIRECTORY}/downloads:/data            
        ports:
            - 8686:8686
        restart: unless-stopped
    nzbget:
        image: ghcr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${CONFIG_DIRECTORY}/nzbget:/config
            - ${STORAGE_DIRECTORY}/downloads:/data
        ports:
            - 6789:6789
        restart: unless-stopped
    plex:
        container_name: plex
        hostname: plex
        image: linuxserver/plex:latest
        restart: unless-stopped
        network_mode: host
        mem_limit: 16384m
        runtime: nvidia
        security_opt:
            - seccomp=unconfined
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - VERSION=latest
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - ${CONFIG_DIRECTORY}/plex/plex_db:/config:rw
            - /dev/shm:/transcode:rw
            - ${STORAGE_DIRECTORY}/video/movie:/mnt/storage/video/movie:rw
            - ${STORAGE_DIRECTORY}/video/tv:/mnt/storage/video/tv:rw
            - ${STORAGE_DIRECTORY}/audio:/mnt/storage/audio:rw
            - ${STORAGE_DIRECTORY}/photos:/mnt/storage/photos:rw            
        devices:
            - /dev/dri:/dev/dri
    tautulli:
        image: ghcr.io/linuxserver/tautulli
        container_name: tautulli
        volumes:
            - ${CONFIG_DIRECTORY}/tautulli:/config
            - ${CONFIG_DIRECTORY}/plex/plex_db/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
        network_mode: host # Removed port binding for network_mode: host
        mem_limit: 4096m
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${CONFIG_DIRECTORY}/bazarr:/config
            - ${STORAGE_DIRECTORY}/video/movie:/movies #optional
            - ${STORAGE_DIRECTORY}/video/tv:/tv #optional
        ports:
            - 6767:6767
        restart: unless-stopped    
    prowlarr:
        image: ghcr.io/hotio/prowlarr
        container_name: prowlarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - UMASK=002
            - TZ=${TZ}
        volumes:
        - ${CONFIG_DIRECTORY}/prowlarr:/config
        ports:
        - 9696:9696
        restart: unless-stopped        
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
            - LOG_LEVEL=info
        ports:
            - 8191:8191
        restart: unless-stopped
    overseerr:
        image: sctx/overseerr
        container_name: overseerr
        environment:
            - LOG_LEVEL=debug
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - PORT=5055 #optional
        ports:
            - "5055:5055"
        volumes:
            - ${CONFIG_DIRECTORY}/overseer/config:/app/config
        restart: unless-stopped
volumes:
    pia-dat:
